### ISSUE TITLE
NBTTag integration

### ISSUE THREAD

**Issue by Taiterio** [NyaaCat/RPGitems-reloaded#110]
Using the vanilla item NBTTags, the plugin can be expanded with features like attack speed and attribute modifiers (Like boots that change the speed value of the wearer or anti-knockback armor).

For me this seems like a great addition, but I'd require some info on how the configuration part of it should work. While I think that Attack Speed can be added in easily along the other attributes, I am unsure on how the others should be configured. 

My current suggestion would be adding a "Modifier" section that can contain any number of attributemodifiers.

You can read up on the tags [here](http://minecraft.gamepedia.com/Tutorials/Command_NBT_tags#Items) and see all attributes that items could potentially modify [here](http://minecraft.gamepedia.com/Attribute).

**Comment by Formula350** [comment]
There are some things to consider for this, based on just my experience with making some customized items using NBTs...

1) The `generic.maxHealth` attribute is handled rather annoyingly by vanilla MC. For example, I created a chestplate that players can obtain which applies an additional 4HP (2 hearts) to the player. This works just fine in general but comes with a rather annoying aspect as well. When wearing the armor, almost every time the player opens and closes their inventory, Minecraft will act as though they have put the armor back on again. What happens as a result is that their health is reset and they have to re-heal those 2 Hearts, but in addition to that as a result of suddenly losing the health and gaining it back, Minecraft thinks you've taken damage and plays the noise as though you were hit. All in all this causes frustration and annoyance by my players as they look around confused wondering why they just lost 2 hearts.

2) Addition of `generic.movementSpeed` could lead to quite undesirable results if not setup properly by servers making items due to RPGItem's own `Power` that uses the Speed Potion Effect.
Example of a possibly bad scenario: 
  Player receives an item with `"generic.movementSpeed",Amount:0.1,Operation:1`, which would give a `10% Speed Boost` to the player (and I believe results in quite a fast movement speed). 
  Player then receives an item with `power potionTick` of `Speed 4`
Due to already having a base modifier of 10%, that Speed 4 is made even *more* powerful than usual. In *other* words, these two things would stack and could lead to unfair conditions in PVP, minigames, or other server events.

That aside, I do ***kinda*** like the idea of being able to stack the NBT speed, but it might be hard to manage and balance out, even IF the Speed `potionTick` is removed (which I think that is a large change to make and would cause lots of problems for server owners like myself). I think a lot of careful consideration is needed before the `movementSpeed` Attribute be added, but that's just my 2cents on the matter :P


***Worth pointing out...*** this could very well be the answer to the whole Strength Potion Effect problem on weapons, by substituting it with `"generic.attackDamage",Operation:0`, which would increase a player's attack damage by an `Addative` amount. Then all you'd need to do is replace each `Effect Level` by an preset-increase of +3 HP damage each level, just like the vanilla Potions do (Potion of Strength does +3 HP, Potion of Strength II does +6 HP). I think ideally it'd be nice to offer the option to set `Operation` values of 0, 1, or 2, to allow servers to configure things however they want. In practice I suspect that most will utilize 0 which will provide far more predictable results. **Keeping in mind** that the "stacking" problem will still be possible here, which is something you do not have to worry about when using the Potion Effects.

Hope that helps some!

**Comment by Taiterio** [comment]
Alright, thanks for the info!

Then it seems like the modifiers might not work as I intended originally, though I think I'd keep them in for any potential server owners to toy around with.

Besides that, I'll run my own tests tomorrow to see what works and would be useful in the context of RPGItems :)

**Comment by Formula350** [comment]
Any progress on this? ;;;) 

There's one thing that'd be nice to be able to do: define the `SkullOwner` tag, to let us change a player head to whatever skin/texture we want. This would be crazy-useful for making `Power Consumable` items, but in my case it'd let us create the Medusa's Head trinket/armor. It is set to give `25% Armor` when worn (does Held count?)*, `Damage Resistance 1` when held/worn, and a `14% Chance to apply Slow` when attacking.

Since the Enchantments seem to stay on RPGItems, I thought *maybe* other NBT data might, so I tried out a theory...
First I generated the Player Skull with the skin I wanted, using:
`/give @p skull 1 3 {display:{Name:"Medusa"},SkullOwner:{Id:"4edf5abb-0ba4-4954-85f8-79113f1da6b4",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2UyN2I0ZGQ0YTMwMzliNzFmN2I2NTY1OWIzYmRjZDcxMzgyODlkM2M2YTNhNjliYTc4YmViY2ZjMWRlNyJ9fX0="}]}}}`
Second, I gave myself the "Medusa's Head" RPGItem.
Third, placed both in a chest, used WorldEdit to create a Schematic
Fourth, I opened the Schematic in NBTExplorer, copied the "SkullOwner" tag from the head obtained via /give, and pasted it in the 'Tag' category for "Medusa's Head".
Fifth, I saved the Schematic, loaded it in WorldEdit, and pasted.

**Results:**
* With RPGItems plugin Enabled: Item reverted back to the vanilla skull:3 item (Player Head)
* With RPGITems plugin *Dis*abled: Item had the texture as expected! However, as soon as RPGItems was loaded it reverted to a vanilla skull:3 :(


Being able to set that NBT via command, such as... `/rpgitem <itemname> skullOwner <base64 code>` would be great.
So as an example:
`/rpgitem medusa skullOwner eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2UyN2I0ZGQ0YTMwMzliNzFmN2I2NTY1OWIzYmRjZDcxMzgyODlkM2M2YTNhNjliYTc4YmViY2ZjMWRlNyJ9fX0=`
* **NOTE:** *I just ran two tests on these skulls to see what are necessary tags needed in order to function. Test #1 was if it works still with any UUID (the `Id:"4edf5abb-0ba4-4954-85f8-79113f1da6b4"` tag from the Give command), so I put in my own UUID; result was it worked and still applied the Medusa skin. Test #2 was with removing the `Id` tag completely: result was a failure and a vanilla skull:3 item with no skin. CONCLUSION: When coded in, as long as it applied to the item a properly formatted UUID, even an invalid UUID like the one in the `/give @p` example, the `base64 code` will work fine!*

Hope that helps :)

**Comment by Formula350** [comment]
(Sorry, my Edit ability isn't working right now...)
First, ignore the "Issue" linking with my `#1` and `#2` stuff, wasn't intended! :\

Just wanted to add in that unfortunately just like that /give example, in the RPGItem command I provided the `base64 code` is always going to be way too long for in-game chat. To use this it'll be ***required*** to use either: Command Block, directly from Console, or editing the Items.yml file directly. Personally I prefer using command block to enter long things, and is what I'd recommend be suggested be used, if my idea is added. :)

**Comment by Taiterio** [comment]
My current problem is finding a good way of implementing this system with as much freedom as possible without making it unnecessarily obstrusive for users. The current plan is to have the standard entries be at the root of the item in question (attack speed, name, etc.) which get written back into a "raw"-NBTTag section which resolves to exactly the format you would enter into the /give command. 

That way, you could alter the raw "code" of the item to add specialized NBTTag values to your item, while potentially making it easier for server owners that are already proficient with NBT based items to alter RPGItems.

The main problem here is that there are NBTTags that are material dependent (Like your SkullOwner example), which I would just leave to the users that know what these tags do. 
Would you be okay with this compromise or would you like an explicit way of setting these values (i.e. check if the skullOwner tag is used on a skull item, is it a valid UUID, etc.) as you suggested above?

I'll be implementing some major changes to the config structure of the items on a seperate branch and report back any findings.

**Comment by Librazy** [comment]
done
