### ISSUE TITLE
Changing how items.yml is saved.

### ISSUE THREAD

**Issue by Nightphoenix16** [NyaaCat/RPGitems-reloaded#111]
Posted this idea in the discussion forum and was told to repost it here:

Could we see items.yml become a folder that has multiple .yml files inside to help organize potentially hundreds of items made?

**Comment by Formula350** [comment]
My 2cents:
At first glance this sounds like it might be a good idea, but you think about it, you're really making it harder on yourself as far as I can tell. Reason being, take my server for example... We have at least 700 items (it's a 576kb items.yml file), some of which are unreleased to the public, some serve functional roles and aren't intended to be used, but most are actually "in service" for players. If each item was simply set with the name (we call it the Raw ID or Raw Name), for example astraeasword.yml, I would have to go into each one to get the details. This is particularly cumbersome due to the fact that in order for you to search up an item you need to know it's Raw ID, so if all I know is a maybe a couple words in the `Lore` or its `Display Name` I'm going to be on an endless search for the item I'm after. 

With the current flatfile, all I do is download it, open it in Notepad++ (or your favorite editing software) and CTRL+F. This is quite useful when you come across instances where a Raw ID isn't as intuitively set in relation to its `Display Name`, as there are a couple items we've made but ended up "recycling" and giving a new `Display Name`. Example we have one that had a Raw ID of `apollolyre`, but it ended up being recycled and has the display name `Golden Fleece`. 

What's *really* needed is a paged `rpgitem list` :P

**Comment by phoenixlzx** [comment]
@Formula350 You need `grep -i 'item name' -R /path/to/rpgitems/items` xD

**Comment by Formula350** [comment]
@phoenixlzx While I may very well have access to the terminal, my 2 head admins do not, nor would either have the knowledge to execute a search. Frankly, neither do it, as this server is my first experience with a Linux system and honestly, I miss the Windows environment we had before :( 

At the end of the day, all I can request is if there is this functionality added to RPGItems, to please set it up where it's a Config option to toggle it, and that *flatfile is left as default*.

Thanks :P

**Comment by Nightphoenix16** [comment]
Having the option to change it as a toggle would be more than enough to help me out. Thanks for discussing it and I look forward to see what you decide to do.

**Comment by Librazy** [comment]
Won't change config file it self for now but may we can have a better way to export/import item or powers.

**Comment by Librazy** [comment]
We also have paged rpgitem list yet

**Comment by Formula350** [comment]
I know this is closed, but I think that it might be helpful to change it where `/rpgitem list` defaults to Page 1 of the output, and where `/rpgitem listall` becomes the new command that displays the entire output in a giant list.
