### ISSUE TITLE
Divide "/rpgitem" results into pages.

### ISSUE THREAD

**Issue by stapleshotz** [NyaaCat/RPGitems-reloaded#116]
When using "/rpgitem" to get the list of commands, it dumps every single command all at once. I'm not even sure if it's even able to display all of them since the MC chat can only store so many lines at once.

My suggestion is to split it into pages that are more navigable and won't flood your chat completely. So "/rpgitem" (or "/rpgitem help" maybe) would give you a page of like 5-10 commands, then "/rpgitem 2" or something to get the next bunch.

Thanks for considering it!

**Comment by Formula350** [comment]
Indeed, it's high time there be a Pages function. My Items.yml is >600KB, and as such we have over 700 items I figure (the ID in the file is at 954). Long long ago we learned there's no point in using the List since only in Console are you able to see it. 

Another suggestion: Search ability. Something perhaps like `/rpgitem list search [ID/Display/Item Type]`. For "id" it would search just the RawID *(item's ID name you use in the command)*, "display" would search only the Display Name of the items, and "item type" would basically let you display only items that full/partial match the MC itemname such as diamond_sword, or just sword to display swords from every material.
