### ISSUE TITLE
People Enchanting armours

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGitems-reloaded#120]
I repoted days ago a issue, sorry for my English. The problem was that player can enchant (using an anvil and a book) armour and they have extra protection, the solution of my ticket was "forbid players from enchanting old rpgitem" but I did not mean "old rpgitem" i mean all the items, so is it posible to forbid players to enchant rpgitem?, the way that they enchant is using an anvil and a Enchanted Book.

Regards,

These are some images.

![8e381ff3c97ea98cfd7633c4b40a0cdf](https://cloud.githubusercontent.com/assets/15118129/15128905/11249740-1604-11e6-8165-1989e1e68ab9.png)
![86bd7d476ba547f231d85be8649400cb](https://cloud.githubusercontent.com/assets/15118129/15128906/12e6852a-1604-11e6-94ad-b36d1fbe63c5.png)

**Comment by Omicronrg9** [comment]
I think It could be problematic.Really needs a switching command for that,like /rpgitem toggleEnchant (something intuitive,like the rest of cmds.).But,what would happen if you want to block,for example Protection,FeathFalling,Highcrit...but you don´t want to block Knockback,Depth Strider or any other enchantment...?
I think there could be servers that don´t want to block all the enchantments,so if there´s a chance to add that switching command,it could be contain another parameter (/rpgitem toggleEnchant [Enchantment]).

**In my opinion,that´s a serious problem which must be resolved ASAP,because people can take advantage of that an cause a game-mechanical break.**
Greetings,Ømicrónrg9

**Comment by RecursiveG** [comment]
Two new permission nodes are added: `rpgitem.allowenchant.new` and `rpgitem.allowenchant.old`
Player who has these permissions can enchant the new/old rpgitems using Enchantment Table and Anvil.
By default, only OPs have these two permissions.

**Comment by iGodGift** [comment]
I have the exact same problem, my players can put enchantments on the rpgitems and after pressing right click they go back to normal with the enchantment and they work just fine...its good for me and the other admins to put enchantments on the items but i dont want players to do that, and they can...how can i prevent it ?
