### ISSUE TITLE
Posible Bug with players in PvP

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGitems-reloaded#227]
Hi, when players are in pvp they cant eat golden apples,

**Comment by DawamRM** [comment]
Bowie hi e.e I have been researching for this problem, trying to solve it for MyCraft, and It has to do with the programación of this program, The only way I would say for you to allow it on your server is to create an RPGitem with the attributes of a Golden Apple. I sent a message to KevinBC, I would like to see if could you please send me your what's app so that way I can inform you If I find something okay? I am DawamRM; helper on your server (Survival RPG 1) hehe I wanted to help but by now, use the RPGitem I sent to KevinBC, and please I would appreciate if you might give me your phone number, I have been researching, and is not only the Gapple, is any food at all. Thx For your time and I do speak Spanish I just felt like writing in English :v. Bye I will try to inform you somehow if I find something okay?

**Comment by DawamRM** [comment]
Programation* Plugin*

**Comment by DawamRM** [comment]
Programation* Plugin*

**Comment by cyilin** [comment]
Are you using 1.9 or 1.10?
this bug has been fixed in 1.11 branch https://github.com/NyaaCat/RPGitems-reloaded/issues/173

**Comment by DawamRM** [comment]
We are using 1.8
