### ISSUE TITLE
一种可以让中立生物跟随的道具

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#28]
如题，只要玩家拿着该道具，就能够让一定范围内的中立生物（包括村民）跟随过来，类似手上拿着种子鸡就聚集过来，或者小麦吸引牛羊那样。当切换成别的道具时候失效。
用途：可以利用这个道具做各种各样有趣（脑洞）的活动。。。

**Comment by RecursiveG** [comment]
Translate: 
Some power that will attract passive mobs(include villagers) within a range. Like seed attracts chicken and wheat attracts cow&sheep. Only works when items are held in hand.

**Comment by Taiterio** [comment]
Sounds like a great idea :D 

The only problem I see is that it would probably require adding some functionality of the minecraft server to alter mob goals without creating custom entities to change the behavior. This would require a handler to keep the plugin version independent.

**Comment by miu-wen** [comment]
那么这样如何，替换成一个可以右键以后将区域内的所有中立生物套上类似缰绳效果的东西，这样让吸引变成牵引，就可以无视掉上诉问题了。。。

**Comment by Taiterio** [comment]
If I understood correctly, you are suggesting to instead create an item that controls neutral mobs since they already have the logic attached to them. The problem would still persist though, making such an idea hard to implement.

I'm currently looking into ways to add this in however, since it is an very interesting idea :)
