### ISSUE TITLE
Attribution rangedonly works incorrectly

### ISSUE THREAD

**Issue by huangwang1003** [NyaaCat/RPGitems-reloaded#289]
Thanks for your perfect plugin, there are some problems when I using it in my server.
Put an item with attribution rangedonly in offhand or the item is bow, then using snow_ball or egg in mainhand. Which will active the item's power, ignore the durability, cooldown and etal.

**Comment by Librazy** [comment]
Activating a power should never bypass durability/cooldown, i needs some more investigation.
For the rangedonly part, it is somehow by design. All projectile launched with a RPGItem in hand which has a ranged/rangedonly / is a bow will be considered as launched by this RPGItem [Events.java#L250 ](https://github.com/NyaaCat/RPGitems-reloaded/blob/d8c5d2926ae357e7da13fd3f7423cd16a2c1c7e1/src/main/java/think/rpgitems/Events.java#L250) . 
That is indeed a issue if you want an item with power projectile should only be active by the projectile launched by itself. If we don't add rangedonly, it can be used in melee;  if we add rangedonly power you can use it with other projectile.
