### ISSUE TITLE
Questions on the items.yml file.

### ISSUE THREAD

**Issue by Kristalyze** [NyaaCat/RPGItems-reloaded#296]
I want to make a wooden pickaxe be able to drop obsidan when I break the block. I saw in the item.yml file that an item can have a customitemmodel, I was wondering on how it works and if I can use it to make an diamond pickaxe looks like a wooden pickaxe??
I have an other problem, I defined customs crafts for tools and sword. For some reasons some of them do not work.
These don't work:
Shovel:
null null Material
null null Stick
null null Stick

Sword:
n n M
n n M
n n  S

Axe:
M M n
M S  n
n  S  n

n M M
n M  S
n  n  S

But the other recipes (witch are exactly like the default Minecraft's recipes) work and I don't know how to fix it.

Thank for your help and sorry for my english.

**Comment by Midnight9746** [comment]
Hi, I'm just some random person on the internet, anyways...

- Custom items typically allows you to use textures from a texture pack

- By custom crafts, I'm assuming you mean the recipes created though the plugin. Okay here's the thing that I've learn, it's best to use the first 3 areas of the chest inventory, like this:

XXXOOOOOO
XXXOOOOOO
XXXOOOOOO

X's being the slots you drop the items in, which you should make sure is on you, before entering the inventory... as it can get buggy and won't really open it back up.. :/

If the items are placed in other slots, it might not even be included in the final recipe. To fix the items, simply remove them, readd, and use the slots I told you about. All the items should work, and if they still don't, (which you can try this now) do '/rpgitem Item recipie 1' which will set the chances of making that item, 100% of the time.

Wooden pickaxes are ment to not break obsidian, but if you want to use a diamond pickaxe, you'll need a resource pack that uses damage values for an unbreakable pickaxe. (Which I mean say a pickaxe has 10 damage points, use like 6 to be the diamond pick texture, but it won't show unless it's unbreakable, which you can use the unbreakable power and durability to set.) However with that, I've only seen it done when you have optifine installed to even see the alternative texture.

If you are able to have many textures for one item, and see them without optifine, then you'll should be set. All there's left to do (I haven't done it before but I'm at least guessing lol) is use that space in the config, to set what textures that item will have when it's supporting a custom item model.

I never really had a reason to set the model, as I just use the enchanting method to make set items change when given a set enchant, as well as just allow it to work with optifine, because why not? (By that, I make it say a sword, but it can only be seen as a say forest sword when you use optifine and is enchanted with silk touch - an enchant that cannot be applied normally). (The item should be a retextured diamond pickaxe as you won't accomplish anything as it would still be wooden)

If you choose to use optifine, an even the enchanting, but don't want to see the enchants on it just do: '/rpgitem Item AddItemFlag HideEnchants'

Anyways, I've seen plugins that changed the rules of pickaxes, such as making it so iron and diamond can break stone, and the rest of the pickaxes cannot. (Which was super annoying, but it prevented rushing, and both iron and diamond broke quickly too), so maybe that can allow you to make wooden pickaxes break obsidian and give the players a haste effect to speed it up. ('/rpgitem item power potiontick 1 haste', that would make it haste 2, and yep confusing but the plugin counts 0 as level 1, if you don't want it to be constant effect use the potionself one and set the cooldown to 0, and the time it's active to above 200 (which is like 10 seconds), although that will make it so players have to right click to use it as a power.

**Comment by Librazy** [comment]
Custom recipe by plugin in 1.12/1.13+ is not recommend. Recipe support in RPGItems main plugin may be removed in future.
