### ISSUE TITLE
Ice power removes block

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#3]
The power `ice` will remove block accidently on hit.

For example, there's a chance to remove the block that is hit from a special position.

Before:
![2015-07-20_14 30 05](https://cloud.githubusercontent.com/assets/1400198/8771100/39b42aba-2eef-11e5-8841-939b2ccddfe7.png)

After:
![2015-07-20_14 30 11](https://cloud.githubusercontent.com/assets/1400198/8771103/4635c41a-2eef-11e5-8818-056517061cf5.png)

So you can see the sign on the chest is removed. The chest can be removed as well during previous test, and items fell out.

**Comment by Taiterio** [comment]
Fixed in commit 87a57203b47a336afd2c581918d8108ed65a9208. The problem was that it set the block where the flying Ice block landed to Ice no matter what material that specific block had. Furthermore, if it found any non solid block while placing the bigger ice cube, it replaced it with ice. The solution to this was to check in both cases if the material to be replaced is neither a sign nor solid. 

If any other blocks have to be added to the list of exclusions or if such a list should be done via config, feel free to reopen this issue :)
