### ISSUE TITLE
Deflecting power not deflecting projectiles back.

### ISSUE THREAD

**Issue by Vyrgax** [NyaaCat/RPGItems-reloaded#358]
# Bug Report
Deflecting power not deflecting projectiles back.

## Describe the Bug
The deflecting power works fine except that it doesn't shoot the projectiles back, only negate the damage.

## To Reproduce
1 Create a RPGItem with the deflect power.
2 Summon a skeleton.
3 Try deflecting it.

### Expected Behavior
The deflect power should shoot the projectile back.

## Environment

- Java version: 8 OpenJ9
- Server software version: 1.13.2 (Spigot)
- RPGItems version: 3.7.584-mc1.13.2.jar

**Comment by Librazy** [comment]
Should be fixed with ed3c76ec in https://github.com/NyaaCat/RPGItems-reloaded/releases/tag/v3.6.593-mc1.13.2

This implementation copy the projectile then destroy the original one, so the projectile may be different with original one. If you are using the Paper server, you can install https://github.com/Librazy/PapeRPGItems/releases for "true deflecting".

The deflect power has two mode: Passive and Active. 
In passive mode, you need to add "HIT_TAKEN" trigger, then you will deflect projectile in your front "facing" (view angle) with a cooldown "cooldownpassive" and a "chance".
In active mode, you need to one of click trigger, then when you clicks, you will deflect projectile in your front "facing" (view angle) in "duration" ticks. Each click "cost" you some durability.
Each deflect cost you "deflectCost" durability. (New in 3.6.596)

**Comment by Vyrgax** [comment]
That fixed it, thanks!
