### ISSUE TITLE
Request:  两段跳

### ISSUE THREAD

**Issue by ncwhale** [NyaaCat/RPGitems-reloaded#41]
It may be a shoes which can let player do a air hike when they are jumping in sky.

May have a cool down counter.

Any idea?

**Comment by ncwhale** [comment]
zh_CN:
大概会是一双鞋子，当玩家装备后可以在空中进行两段跳喵。

可能需要一个冷却计时器。

**Comment by Taiterio** [comment]
Do you mean something like a double jump or more of a dash? Sounds good, but sadly cannot be bound to the player jump since it doesn't work in the air :/

**Comment by phoenixlzx** [comment]
Why not just put a block (configurable?) under the player foot for several seconds so player could jump again (in the air)?

**Comment by Taiterio** [comment]
The problem with that would be figuring out when to place the blocks (most likely a check of when the players y-velocity turns negative again), though I think a more natural way of implementing this would be to use the PlayerToggleFlightEvent which is triggered on a double tap of the jump button. To do that all players would need to have flying allowed however, otherwise this event is not called.

This would need some kind of way to track players using the power, as checking the PlayerMoveEvent for jumps may cost alot of performance.

**Comment by phoenixlzx** [comment]
I watched a video today, a player hold a bow with high level knock back enchant, jump up and then shoot himself with the bow.

Though I dont know how he could shoot himself, but the knockback effect can be applied to a player in the air. With this effect, the double jump power may be implemented.

**Comment by RecursiveG** [comment]
@phoenixlzx The "jump" effect can be easily achieved by setting the velocity of the player from the code. The problem is how to detect when player "trigger" the jump. Hit space won't trigger any events on the server if the player is in the air, so it cannot be detected.

**Comment by phoenixlzx** [comment]
Then just 'use' it, jump then right or left click to get the boost effect.

**Comment by Librazy** [comment]
@美羽的火箭
