### ISSUE TITLE
How do I use Conditions?

### ISSUE THREAD

**Issue by RedPxnda** [NyaaCat/RPGItems-reloaded#415]
How do I use conditions for powers? On the wiki it doesn't show how, and I have tried many ways but it doesn't seem to work. Please help.

P.S. Also, many things on the wiki look weird and say MISSING_LANG<something written here>

**Comment by ReinWD** [comment]
Things on wiki is out dated.
Lately we are focusing on feature development & bug fixes.

MISSING_LANG means that the language file is missing corresponding section in your <lang>.yml.
try to fetch a new one([like this](https://github.com/NyaaCat/RPGItems-reloaded/blob/1.15/src/main/resources/lang/en_US.yml)), or try to understand what message it means(usually it's a hint).

Conditions & marker is seperated from power since v3.8. it can give you a better experience. Conditions can determine whether a power should run or not.

simply add a condition and give it an `id` and you can use `id` in your powers' `condition` section.

**Comment by RedPxnda** [comment]
thx so much! <3
