### ISSUE TITLE
More Attributes [Suggestion]

### ISSUE THREAD

**Issue by Azraq** [NyaaCat/RPGitems-reloaded#59]
Hello, i recently came across this plugin and honestly i am quite impressed by the light weight and performance fo this plugin. This has great protential so here i may suggest some more attributes that can be added to make it even more awesome.

 1-) **Health** 
      desc: Health would add hitpoints to you by wearing the item or holding it in your hand.

 2-)*\* Dodge**
      desc: Player holding/wearing item would get a percentage of dodging an attack chance from 0 - 100%

 3-)*\* Block**
      desc: It's same as dogde but each time a player blocks an attack he/she would get a slow effect for 1-3 seconds(configurable).

 4-) **Reflect**
      desc: It's same as Block but instead of giving the blocker slowness effect it gives the attacker a slowness effect.

 5-) **Weapn Speed**
      desc: It changes the attack speed of the item,. e.g. sword,pickaxe,axe,shovel..etc

:p whether you add or not, you guys are doing great work on this project and i hope you keep doing so. my sincere than

**Comment by Taiterio** [comment]
Nice suggestions! 

There would only be a problem with Weapon Speed pre 1.9, as the only way to add this would to change how often you could damage an enemy (by reducing/increasing the enemy invulnerability ticks).

**Comment by Formula350** [comment]
We somewhat achieve the speed request on my server, though unfortunately it's a bit restricted to Tools that we've set to be weapons. Example: Axes as Axes, Shovels as Clubbing weapons, Hoes as Scythes. What we do is simply add the Fast Digging or Slow Digging to the powers, causing them to swing more or less often, respectively.

Spanning this over to Swords, and maybe even Bows (though I suspect Draw speed isn't modifiable?), would be really nice.
*(I'm not sure when I'll be able to move my server over to 1.9 since some plugins are abandoned and cease to function in 1.9)*
