### ISSUE TITLE
Let users add languages

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#6]
Currently all languages are included in source code, I think we should let users create languages file so they don't need to wait new language support and all messages can be customized.

For example, create a directory in config root called `lang` and contains all message language files such as `en_US.lang`, `de_DE.lang` and `zh_CN.lang` ..., so that users can update those files or create new languages files on their own.

**Comment by Taiterio** [comment]
My first approach would be to copy the whole folder already present in the source into the config folder of the plugin. Then players just set their languages and configure it appropriately. Users can then write a pull request to add their language to the repo if the language is not included yet.

I'll be working on this one tomorrow :)

**Comment by Taiterio** [comment]
Getting some issues with the config not currently reading the language that has been set and there are still some problems with getting the strings that belong to the language. Other than that, the system for copying and loading all languages found in the source code is now in and will be included once all other errors with the system have been fixed :)

**Comment by Taiterio** [comment]
Added in a1824a8edb01b941247ef65527eb28e451dec3a9. As noted earlier, the locale folder is now exported from the plugin jar into the plugins folder, which means that anyone can use pull requests to bring in their own default languages to the project :)

I also removed the broad usage of locales everywhere, aswell as the per-player locales, since neither were really implemented in a meaningful way.

If the feature of having individual players choose the language they see items and messages in, that could be added in a more central fashion (i.e. attaching the locale to messages and items in one class rather than in the whole project).
