### ISSUE TITLE
Armor Help

### ISSUE THREAD

**Issue by CopperGenie** [NyaaCat/RPGitems-reloaded#96]
Is the armor percentage the percent of the whole armor bar? Like, if a piece of armor has 20% armor, does it have armor equivalent to 20% of the armor bar (i.e. 4 points)?

**Comment by RecursiveG** [comment]
It reduces the total damage by 20%.
But I haven't tested this feature in game and some other adjustments may affect the result.

**Comment by Formula350** [comment]
In the past we've setup "Event" armor for the sole purpose of protecting one of my staff members to make them able to survive multiple attackers, and I can tell you that having a full set of Chainmail Armor set at 50% is able to endure quite a beating.

For player armor we usually set the individual pieces in the 20-35% range, with our current higher-end weapons set anywhere in the 20-30dmg range. On top of that we have the base player's health set to 2-rows, and all of that combined makes for a fairly well balanced PVP (we're an RPG server).

For a long time I had wondered how specifically it calculates and applies the % of Armor, but in the end gave up trying to figure it out and just went with the old trial-and-error approach. In the very very beginning (over 2 years ago) we had Skeleton Armor set to 75% (on roughly each of the 4 pieces, Iron BTW), but it would make you invincible against everything, so it ended up getting dropped down to 20%. I can't say for certain but I **think** that not even the type of armor matters, it's solely the Armor% that it is based on.

**Comment by RecursiveG** [comment]
@Formula350 If multiple armors are equipped, the damage reduction will stack. Four 20% armors will make the damage be `0.8 * 0.8 * 0.8 * 0.8 ≈ 41%` of original. And four 75% armors will be `0.25 * 0.25 * 0.25 * 0.25 ≈ 0.39%` which is almost invincible

**Comment by CopperGenie** [comment]
Okay, thanks. I have another problem though with leather armor. If I use leather armor pieces as the 'item' for a rpgitem, it automatically dyes it black. Is there a way to prevent this or change the color of the 'item'?

**Comment by Formula350** [comment]
You can change the item's color by using a Hex colorcode value (there are various sites on Google that are good for this, just search for "Hex color codes"), but it's a bit tricky and more importantly a bit annoying, as it requires the server to restart before the color is applied (in all my past experience). Since `/rpgitem reload` is a more recent addition, that *might* do the trick, but I don't know how safe it is to use when you get up there in created items or online players. (long ago I could use PlugMan to safely reload RPG after I made an edit to the Items.yml, but later on it started causing errors, but I have no clue if it was due to our item database growing substantially or simply bukkit releases)

My server's address is: **pj.crafterslegacy.com** (or **.net**), website is the same, but **www.**

**Comment by CopperGenie** [comment]
@Formula350 Where in the command do I input the hex code?

**Comment by RecursiveG** [comment]
You are free to continue this discussion.
